### ISSUE TITLE
Command: Open settings

### ISSUE THREAD

**Issue by nelsam** [nelsam/vidar#179]
### Description

When a user wants to edit their config, they should be able to easily open the config files without necessarily knowing where they are located.

Follow-up for #15 

### Expected behavior

I can open the config files without knowing their exact location.

### Actual behavior

I need to know the config files' location to edit them.

### Subtasks

* [ ] I can open my project list with a single command
* [ ] I can open the main settings file with a single command
* [ ] There is a UI showing the config files that vidar is reading from
  * [ ] I can navigate these files with the keyboard
  * [ ] I can navigate these files with the mouse
