### ISSUE TITLE
Hook: Config file details

### ISSUE THREAD

**Issue by nelsam** [nelsam/vidar#180]
### Description

In addition to standard yaml/toml/json highlighting, we need to provide some additional information for files that vidar loads as settings files.

Follow-up for #15 

### Expected behavior

Opening a settings file shows me information about how it affects vidar

### Actual behavior

Opening a settings file shows the raw file

### Subtasks

* [ ] Config file entries with available documentation show the documentation in the editor.
* [ ] Config file entries which are overridden by a higher priority config file (e.g. `~/.config/vidar/settings.toml` should override `/etc/vidar/settings.toml`) are greyed out and link to the currently-in-use file
* [ ] Config file entries in un-writeable locations (e.g. `/etc/vidar/settings.toml` is usually not writeable without root permissions) link to locations that _are_ writeable.
